apiVersion: v1
kind: Service
metadata:
  name: watchlist-service
  labels:
    app: watchlist
spec:
  type: NodePort
  selector:
    app: watchlist
  ports:
    - name: http
      port: 80
      targetPort: 8000